# Change these first
owner: pudding-keep-in-touch # Your GitHub organization or username, where this repository lives
repo: keep-in-touch-upptime # The name of this repository

sites:
  - name: keepintouch.me
    url: 	https://keep-in-touch.me

  # - name: www.keepintouch.me
  #   url: 	https://www.keep-in-touch.me:3000
  # - name: pro-be.keepintouch.me
  #   url: 	http://pro-be.keep-in-touch.me:3000
  # - name: pro-db.keepintouch.me
  #   url: 	https://pro-db.keep-in-touch.me:5432
    
  - name: dev-fe.keepintouch.me
    url: 	http://dev-fe.keep-in-touch.me
    port: 3000
  - name: dev-be.keepintouch.me
    url: 	http://dev-be.keep-in-touch.me
    port: 3000
  - name: dev-db.keepintouch.me
    url: 	https://dev-db.keep-in-touch.me
    port: 5432
    
  - name: Puddingcamp
    url: https://puddingcamp.com
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.co
  - name: IPv6 test
    url: forwardemail.net
    port: 80
    check: "tcp-ping"
    ipv6: true

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /pudding-keep-in-touch
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: keep-in-touch
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
